---
# Secret
apiVersion: v1
kind: Secret
metadata:
  name: storageos-api
  namespace: storageos
  labels:
    app: storageos
type: Opaque
data:
  password: c3RvcmFnZW9z # echo -n <username> | base64
  username: c3RvcmFnZW9z # echo -n <username> | base64
---
# CR cluster definition
apiVersion: storageos.com/v1
kind: StorageOSCluster
metadata:
  name: storageos-cluster
  namespace: "storageos"
spec:
  secretRefName: "storageos-api"
  secretRefNamespace: "storageos"
  k8sDistro: "upstream"
  storageClassName: storageos
  images:
    nodeContainer: us-central1-docker.pkg.dev/shaped-complex-318513/ondat/node:v2.5.0-beta.1
    apiManagerContainer: us-central1-docker.pkg.dev/shaped-complex-318513/ondat/api-manager:v2.5.0-sync
    initContainer: us-central1-docker.pkg.dev/shaped-complex-318513/ondat/init:v2.1.0
    csiNodeDriverRegistrarContainer: us-central1-docker.pkg.dev/shaped-complex-318513/ondat/csi-node-driver-registrar:v2.1.0
    csiExternalProvisionerContainer: us-central1-docker.pkg.dev/shaped-complex-318513/ondat/csi-provisioner:v2.1.1-patched
    csiExternalAttacherContainer: us-central1-docker.pkg.dev/shaped-complex-318513/ondat/csi-attacher:v3.1.0
    csiExternalResizerContainer: us-central1-docker.pkg.dev/shaped-complex-318513/ondat/csi-resizer:v1.1.0
    csiLivenessProbeContainer: us-central1-docker.pkg.dev/shaped-complex-318513/ondat/livenessprobe:v2.2.0
    kubeSchedulerContainer: us-central1-docker.pkg.dev/shaped-complex-318513/ondat/kube-scheduler:v1.20.5
  kvBackend:
    address: "storageos-etcd-client.storageos-etcd:2379"
  resources:
    requests:
      memory: "1Gi"
      cpu: 1
#  nodeSelectorTerms:
#    - matchExpressions:
#      - key: "node-role.kubernetes.io/worker" # Compute node label will vary according to your installation
#        operator: In
#        values:
#        - "true"
